### ISSUE TITLE
Support Array Symbolics in ReactionSystem

### ISSUE THREAD

**Issue by aspecht1** [SciML/Catalyst.jl#336]
Hello everyone,

I am currently trying to create a chemical network in Catalyst.jl using my own functions as reaction rates. These functions are provided species of the network as input arguments and then need to use if statements and the `floor(x)` function on them. Here is a very simplified example, which causes no error:

```
using Catalyst

function f(A, dummy)
    
    @show typeof(A)
    if A > 10
        out = 0
    else
        out = 1
    end
    return out
end

@register f(A, dummy)
network = @reaction_network begin

    f(A, 1), A ⇒ B
    
end
```

The ouput is the usual Latexified presentation of the single reaction.
The problem occurs when I pass arrays or tuples to my function like this:

```
using Catalyst

function f(A, dummy)
    
    @show typeof(A)
    if A > 10
        out = 0
    else
        out = 1
    end
    return out
end

@register f(A, dummy)
network = @reaction_network begin

    f(A, [1]), A ⇒ B
   
end
```

Then I get this error:

```
typeof(A) = Num
TypeError: non-boolean (Num) used in boolean context

Stacktrace:
 [1] f(::Num, ::Array{Int64,1}) at .\In[5]:6
 [2] top-level scope at In[5]:15
 [3] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091
```
For some reason, if I pass an array to my function it will turn my other arguments into this `Num` data type, which comes from Symbolics.jl I think, and cant be used in logical operations. I know about the IfElse.jl package but there is no alternative/solution for the `floor(x)` function (as far as I know), which cannot use `Num` aswell.

So what I want is to just pass the arguments as `Float64` so I can do whatever I want if them.

The easiest solution of course would be to just not use arrays but pass all the arguments/species individually. But for large numbers of arguments (11-15) it takes ages to `@register` the function. The code runs forever, I dont know exactly how long it would take to register a function with 15 arguments. This “registering problem” may be worth its own post.

Maybe its noteworthy that in the first example code `typeof(A)` is not being printed, only in the second example “`typeof(A) = Num`” is being printed. I dont know what that means or if it means anything.

I feel like this interaction between arrays and Num is not intended. Whether I pass an array or not shouldnt change the datatype of the other arguments.

I hope I included all you guys need to know, this is my first post. Thank you !

I also posted this on https://discourse.julialang.org/t/catalyst-weird-interaction-between-user-defined-functions-arrays-and-num/61867

**Comment by ChrisRackauckas** [comment]
>The easiest solution of course would be to just not use arrays but pass all the arguments/species individually. But for large numbers of arguments (11-15) it takes ages to @register the function. The code runs forever, I dont know exactly how long it would take to register a function with 15 arguments. This “registering problem” may be worth its own post.

You'd be defining 15! functions. I think this just needs array variables.

**Comment by aspecht1** [comment]
Hi Chris, thank you for your fast reply!
Unfortunately Im not quite sure what you mean by array variables. Something like `@variables t H H2 H2O species[H, H2, H2O](t)`?
I cannot figure out how to make that work. I get the error `KeyError: key 'H' not found`
Im looking for a way to pass an array, containing my states/species, to my reaction rate function without getting `TypeError: non-boolean (Num) used in boolean context`. Is that possible?

**Comment by isaacsas** [comment]
@aspecht1 what about if you do
```julia
network = @reaction_network begin
           f(A, Num(1)), A ⇒ B           
       end
```

**Comment by aspecht1** [comment]
> @aspecht1 what about if you do
> 
> ```julia
> network = @reaction_network begin
>            f(A, Num(1)), A ⇒ B           
>        end
> ```
> 
> edit: Nevermind, I missed that it needs to be an array...

But what would `Num(1)` do? The point is, that I dont want my input to be treated as Num.

**Comment by aspecht1** [comment]
I still have this problem. Does anyone have an idea how to pass ten to fifteen arguments to a user defined reaction rate function? What does @ChrisRackauckas mean by:
> I think this just needs array variables.

If I pass an array to my reaction rate function I get `TypeError: non-boolean (Num) used in boolean context`. If I pass my arguments individually (instead of using an array), it takes to much time to register the function in the first place.

**Comment by isaacsas** [comment]
@aspecht1 your example works fine if you use the `IfElse` package right? So the issue is really just about using `ceil` and `floor`? That seems to be a Symbolics.jl issue. It looks like a PR was just added 

https://github.com/JuliaSymbolics/Symbolics.jl/pull/257

in Symbolics.jl that adds support for them. Can you try out the Symbolics master and see if your issue is now fixed?

**Comment by ChrisRackauckas** [comment]
Should be on Symbolics.jl release now.

**Comment by aspecht1** [comment]
Well `floor` works now with the latest version of Symbolcis  (thank you!), but the reason I need `floor` is to use `Int(floor(x))` as an array index. And `Int64(::Num)` of course does not work.

But I feel like my issue is not solved by using `IfElse` or registering functions to Symbolics.
If my reaction rate looks like `f(A, B)` I dont need `IfElse` or the updated Symbolics version. Everything works fine.
The problems only occur if I do `f([A, B])`, which I have to do, otherwise `@register f` takes too long. In that case I am getting all the "`MethodError: no method matching "some function"(::Num)`" errors. Why is that?

**Comment by isaacsas** [comment]
@aspecht1 your issues here seem more related to limitations of Symbolics.jl tracing when using arrays, and less a Catalyst issue (Catalyst just leverages whatever Symbolic functionality Symbolics.jl provides). @ChrisRackauckas would it make sense to transfer this over to Symbolics?

**Comment by ChrisRackauckas** [comment]
Just for you https://symbolics.juliasymbolics.org/dev/manual/faq/#Transforming-my-function-to-a-symbolic-equation-has-failed.-What-do-I-do?-1

**Comment by aspecht1** [comment]
I feel honored, thank you for all your effort. I'm sure this will help many though.
But I guess this issue will stay open, until 'Support Array Symbolics in ReactionSystem' is here.
That would really help my thing.

**Comment by ChrisRackauckas** [comment]
Yeah array symbolics just merged yesterday. The docs are up:

https://symbolics.juliasymbolics.org/dev/manual/arrays/

Support now needs to be propagated to ModelingToolkit and all modeling languages (i.e. Catalyst).

**Comment by aspecht1** [comment]
So I read through the docs and I am not quite sure how this will affect Reaction Systems.
Will this update change how `f([A, B]), A -> B` works? At the moment this will give rise to the famous 
`ERROR: TypeError: non-boolean (Num) used in boolean context`, if you access the arrays elements and do logical operations/`floor()`/`Int()` etc. to it.
While with `f(A, B), A -> B` you can do all of that with `A` or `B` (without `@register`ing `floor()`/`Int()`).

**Comment by isaacsas** [comment]
@aspecht1 you might get more traction making an issue in Symbolics.jl and discussing exactly what you want to do there (with converting things to an `Int` and such). Here is a MWE that shows the problem with your original example isn't really a Catalyst issue (currently):
```julia
using Symbolics
@variables t A(t)
function f(A, dummy)
    @show typeof(A)
    if A > 10
        out = 0
    else
        out = 1
    end
    return out
end
@register f(A, dummy)
f(A,[1])
```
giving
```
typeof(A) = Num
ERROR: TypeError: non-boolean (Num) used in boolean context
Stacktrace:
```

On the other hand the following example which uses arrays, but avoids conditional logic which is unsupported by Symbolics.jl, seems to work
```julia
function g(A)
  A[1] + A[2] + A[3]
end
@register g(A)
network = @reaction_network begin
    g([A,B,1.0]), A ⇒ B
end
```

I'm going to close this as I don't think there is anything currently to be done in Catalyst. However, please feel free to let me know if you have an explanation / example of something like this that works using arrays in Symbolics.jl but doesn't work in Catalyst and we can reopen and try to fix it.
